# Generated by Django 6.0.3 on 2026-03-10 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contabilidad', '0001_initial'),
        ('Profesores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profesores.profesor'),
        ),
        migrations.AddField(
            model_name='detallenomina',
            name='nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contabilidad.nomina'),
        ),
    ]
