# Generated by Django 6.0.3 on 2026-03-10 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contabilidad', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='plantel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plantel'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Contabilidad.periodo'),
        ),
        migrations.AddField(
            model_name='recibonomina',
            name='nomina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Contabilidad.nomina'),
        ),
    ]
