# Generated by Django 6.0.3 on 2026-03-10 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contabilidad', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vistaprevianomina',
            name='generado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vistaprevianomina',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contabilidad.periodo'),
        ),
        migrations.AddConstraint(
            model_name='periodo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTO')), fields=('plantel',), name='un_periodo_abierto_por_plantel'),
        ),
    ]
