# Generated by Django 6.0.3 on 2026-04-26 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0004_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='plantel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.plantel'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='tipo',
            field=models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='QUINCENAL', max_length=10),
        ),
    ]
