# Generated by Django 6.0.3 on 2026-05-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0005_alter_periodo_plantel_alter_periodo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('pagada', 'Pagada')], default='procesando', max_length=20),
        ),
    ]
