# Generated by Django 6.0.3 on 2026-05-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0006_nomina_estado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='periodo',
            name='un_periodo_abierto_por_plantel',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='plantel',
        ),
    ]
