# Generated by Django 6.0.3 on 2026-03-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('JUSTIFICACION', 'Justificacion'), ('CORRECCION', 'Correccion'), ('TRANSFERENCIA', 'Transferencia'), ('CAPTURA_MANUAL', 'Captura manual')], max_length=15)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
    ]
