# Generated by Django 6.0.3 on 2026-03-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miercoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sabado')], max_length=3)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.CharField(max_length=10)),
                ('es_hora_clase', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13)),
                ('curp', models.CharField(max_length=18)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.TextField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('estado_laboral', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('BAJA_TEMPORAL', 'Baja temporal'), ('BAJA_DEFINITIVA', 'Baja definitiva')], default='ACTIVO', max_length=20)),
                ('costo_por_hora', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tipo_contrato', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
