# Generated by Django 6.0.3 on 2026-03-10 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profesores', '0001_initial'),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.departamento'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='plantel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plantel'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horario',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profesores.profesor'),
        ),
        migrations.AddField(
            model_name='transferenciadepartamento',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferenciadepartamento',
            name='departamento_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='users.departamento'),
        ),
        migrations.AddField(
            model_name='transferenciadepartamento',
            name='departamento_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origen', to='users.departamento'),
        ),
        migrations.AddField(
            model_name='transferenciadepartamento',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profesores.profesor'),
        ),
    ]
