# Generated by Django 6.0.3 on 2026-03-11

from django.db import migrations, models


def copy_profesor_plantel_to_m2m(apps, schema_editor):
    Profesor = apps.get_model("Profesores", "Profesor")
    for profesor in Profesor.objects.all():
        if getattr(profesor, "plantel_id", None):
            profesor.planteles.add(profesor.plantel_id)


def restore_profesor_plantel_from_m2m(apps, schema_editor):
    Profesor = apps.get_model("Profesores", "Profesor")
    for profesor in Profesor.objects.all():
        first = profesor.planteles.first()
        if first is not None:
            profesor.plantel_id = first.id
            profesor.save(update_fields=["plantel_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("Profesores", "0002_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesor",
            name="planteles",
            field=models.ManyToManyField(related_name="profesores", to="core.plantel"),
        ),
        migrations.RunPython(
            copy_profesor_plantel_to_m2m,
            reverse_code=restore_profesor_plantel_from_m2m,
        ),
        migrations.RemoveField(
            model_name="profesor",
            name="plantel",
        ),
    ]
