# Generated by Django 6.0.3 on 2026-03-12 15:25

from django.db import migrations, models


def forwards_copy_departamento(apps, schema_editor):
    Profesor = apps.get_model("Profesores", "Profesor")
    for profesor in Profesor.objects.all():
        if getattr(profesor, "departamento_id", None):
            profesor.departamentos.add(profesor.departamento_id)


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Profesores', '0003_profesor_planteles'),
        ('users', '0002_seed_roles_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='departamentos',
            field=models.ManyToManyField(related_name='profesores', to='users.departamento'),
        ),
        migrations.RunPython(forwards_copy_departamento, backwards_noop),
        migrations.RemoveField(
            model_name='profesor',
            name='departamento',
        ),
    ]
