# Generated by Django 6.0.3 on 2026-03-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesores', '0004_remove_profesor_departamento_profesor_departamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
