# Generated by Django 6.0.3 on 2026-03-23 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesores', '0005_horario_activo'),
        ('core', '0002_initial'),
        ('users', '0003_update_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='curp',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='rfc',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['profesor', 'dia_semana', 'activo'], name='Profesores__profeso_f6e90c_idx'),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['profesor', 'es_hora_clase', 'activo'], name='Profesores__profeso_dbc3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['dia_semana', 'es_hora_clase', 'activo'], name='Profesores__dia_sem_ae2699_idx'),
        ),
        migrations.AddIndex(
            model_name='profesor',
            index=models.Index(fields=['estado_laboral'], name='Profesores__estado__84e44b_idx'),
        ),
        migrations.AddIndex(
            model_name='profesor',
            index=models.Index(fields=['fecha_ingreso'], name='Profesores__fecha_i_a486db_idx'),
        ),
        migrations.AddIndex(
            model_name='transferenciadepartamento',
            index=models.Index(fields=['profesor', 'fecha'], name='Profesores__profeso_d1c9d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('profesor', 'dia_semana', 'hora_inicio', 'hora_fin'), name='unique_horario_profesor_bloque'),
        ),
    ]
