# Generated by Django 6.0.3 on 2026-05-13 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesores', '0006_alter_profesor_curp_alter_profesor_rfc_and_more'),
        ('core', '0002_initial'),
        ('users', '0003_update_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='departamentos',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='planteles',
        ),
        migrations.AddField(
            model_name='profesor',
            name='departamento',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='profesores', to='users.departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='plantel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='profesores', to='core.plantel'),
            preserve_default=False,
        ),
    ]
