# Generated by Django 6.0.3 on 2026-03-10 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Asistencias', '0002_initial'),
        ('Profesores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profesores.horario'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profesores.profesor'),
        ),
        migrations.AddField(
            model_name='correccionasistencia',
            name='aprobada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correccionasistencia',
            name='asistencia_compensatoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensaciones', to='Asistencias.asistencia'),
        ),
        migrations.AddField(
            model_name='correccionasistencia',
            name='asistencia_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones', to='Asistencias.asistencia'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='asistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencias.asistencia'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenciaincidencia',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencias.incidencia'),
        ),
        migrations.AddField(
            model_name='solicitudcorreccion',
            name='aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudcorreccion',
            name='asistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Asistencias.asistencia'),
        ),
        migrations.AddField(
            model_name='solicitudcorreccion',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profesores.profesor'),
        ),
    ]
