# Generated by Django 6.0.3 on 2026-03-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencias', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
