# Generated by Django 6.0.3 on 2026-03-21 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencias', '0004_alter_asistencia_hora_salida'),
        ('Profesores', '0005_horario_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('RETARDO', 'Retardo'), ('FALTA', 'Falta'), ('JUSTIFICADA', 'Justificada')], max_length=25),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profesores.horario'),
        ),
    ]
