# Generated by Django 6.0.3 on 2026-04-17 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencias', '0005_alter_asistencia_estado_alter_asistencia_horario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['estado'], name='Asistencias_estado_a584f7_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['solicitante'], name='Asistencias_solicit_914afa_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['fecha_solicitud'], name='Asistencias_fecha_s_3f93ff_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['asistencia', 'estado'], name='Asistencias_asisten_372554_idx'),
        ),
    ]
