# Generated by Django 6.0.3 on 2026-05-11 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencias', '0006_incidencia_asistencias_estado_a584f7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='asistencia_original',
            field=models.ForeignKey(blank=True, help_text='Falta original que esta clase compensatoria está cubriendo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensatorias', to='Asistencias.asistencia'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='asistencia_compensatoria',
            field=models.OneToOneField(blank=True, help_text='Asistencia compensatoria generada al aprobar esta incidencia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencia_origen', to='Asistencias.asistencia'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('RETARDO', 'Retardo'), ('FALTA', 'Falta'), ('JUSTIFICADA', 'Justificada'), ('COMPENSATORIA', 'Compensatoria')], max_length=25),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='tipo_registro',
            field=models.CharField(choices=[('RELOJ', 'Reloj'), ('MANUAL', 'Manual'), ('COMPENSATORIA', 'Compensatoria')], default='RELOJ', max_length=15),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='asistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='Asistencias.asistencia'),
        ),
    ]
