# Generated by Django 6.0.3 on 2026-05-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='Notificatio_usuario_3e1165_idx',
            old_name='Notificatio_usuario_425873_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='Notificatio_usuario_27eb2e_idx',
            old_name='Notificatio_usuario_1389e0_idx',
        ),
    ]
